### ISSUE TITLE
Rotation on Lshift axis (whichever it is) finicky

### ISSUE THREAD

**Issue by SplitMilky** [BruceOfTheBow/BruceComfyMods#10]
ComfyGizmo

Rotating holding left shift seems to work 3% of the time.   I moved a floor board to and angle i wanted and swtiched to a chest and i could not restore or move the angle at all using left shift anymore.  I switch back to floorboards to test it and still could not rotate with shift.   It does switch and show me the axis when i hold shift but just does not rotate.

![image](https://github.com/BruceOfTheBow/BruceComfyMods/assets/81430176/bb25db1c-0f79-436c-b800-f2550e9c7d8d)
![image](https://github.com/BruceOfTheBow/BruceComfyMods/assets/81430176/59e6fd69-81f5-4080-97b3-408c1c7fe87c)

Maybe because I am using newer BepInEx,  ill downgrade and report back later.

**Comment by BruceOfTheBow** [comment]
Not sure where that version of BepInEx comes from. ComfyGizmo is tested against https://thunderstore.io/c/valheim/p/denikson/BepInExPack_Valheim/. Please open a new issue if the bug persists with this version of BepInEx.

**Comment by SplitMilky** [comment]
That is the latest version of [BepInEx ](https://github.com/BepInEx/BepInEx/releases)from their git. It is odd you don't know that.   Regardless,  it is working fine now.  

Started working properly once I ditched Vortex for managing or when I got rid of infinity hammer.

**Comment by BruceOfTheBow** [comment]
Great, glad there is no issue. I would recommend using the community managed Valheim version of BepInEx linked above for the reasons outlined there. It's odd you would use something else.

**Comment by SplitMilky** [comment]
I think I did use community at first but I was getting all kinds of issues which I think were the result of Vortex.

If I have any future issues I'll revert BepInEx.
________________________________
