### ISSUE TITLE
ComfyQuickSlots bug

### ISSUE THREAD

**Issue by Frixen** [BruceOfTheBow/BruceComfyMods#11]
![image](https://github.com/BruceOfTheBow/BruceComfyMods/assets/18544029/53c2ef54-e87e-4902-b8a9-c2617d058154)

Sometimes it happens that random items from the inventory are put in place of Utils or any other additional slot (probably this happens at the time of raising the tombstone after death), as a result of which they cannot be removed from these slots (only if replaced with an item suitable for the slot), but after that it is not possible it turns out to throw out an item from the inventory that was in an additional slot because it is considered equipped

**Comment by BruceOfTheBow** [comment]
Please provide your logOuput file and/or all mods that are being used when this occurs.. Does this happen with only ComfyQuickSlots installed? Thanks
