### ISSUE TITLE
Gizmo - Minor Compat quirk with advancedterrainmodifiers - visual

### ISSUE THREAD

**Issue by Kherae** [BruceOfTheBow/BruceComfyMods#13]
gizmo can rotate the tool ghosts from advancedterrainmodifiers by searica. doesnt seem to actually affect anything other than the visibility of the ghosts (which  looks silly)

**Comment by BruceOfTheBow** [comment]
I will take a look at adding a config option to disable and/or reset rotations for non-hammer building tools.

**Comment by Kherae** [comment]
definitely sounds like a good change

**Comment by searica** [comment]
A config setting in ComfyGizmo would be great! I've actually been considering adding a compatibility patch to `AdvancedTerrainModifiers` that undoes whatever rotations Gizmo applies to terrain modification pieces when using the Hoe or similar placement tools added by other mods.

**Comment by redseiko** [comment]
Added new config option `[Ignored] ignoreTerrainOpPrefab` to `v1.13.0`. When enabled, Gizmo rotation will be ignored for prefabs that have a TerrainOp component.

https://thunderstore.io/c/valheim/p/ComfyMods/Gizmo/
