### ISSUE TITLE
[ValheimRAFT] compatibility with dynamic rotation

### ISSUE THREAD

**Issue by zolantris** [BruceOfTheBow/BruceComfyMods#14]
Hello! Opening a help question here to see if we can figure a way to make these two mods compatible with each-other. 

- Currently players on rafts/ships must disable floatation and have a parent rotation for X=0 and z=0 otherwise Gizmo will not align with raft.

## The Code

ValheimRAFT patches only relative rotations related to base-game calls of  `Quaternion.Euler` is the only call that is changed when patching `Player.UpdatePlacementGhost`. [Here is the section](https://github.com/zolantris/ValheimMods/blob/main/src/ValheimRAFT/ValheimRAFT.Patches/Player_Patch.cs#L347-L363).

This transpiler method is not enough to fix other rotation mods including gizmo if they do not call `Quaternion.Euler`. Makes this approach a bit too brittle.

Guessing this may only be the first part of the issue too. IE after ghost placement there might be additional logic that needs overrides.

**Comment by BruceOfTheBow** [comment]
ComfyGizmo transpiles the Quaternion value returned from the Quaternion.Euler() call that is used in the rest of UpdatePlacementGhost. Merely patching Quaternion.Euler will indeed result in the calculations done in ValheimRAFT being overwritten.

https://github.com/BruceOfTheBow/BruceComfyMods/blob/5dee1e82148ce8dbb36ea5fb11375e6ecb9845dd/ComfyGizmo/Patches/PlayerPatch.cs#L93-L107

**Comment by BruceOfTheBow** [comment]
For compatibility you could check if Gizmo is installed, then conditionally patch [RotationManager.GetRotation()](https://github.com/BruceOfTheBow/BruceComfyMods/blob/5dee1e82148ce8dbb36ea5fb11375e6ecb9845dd/ComfyGizmo/Core/RotationManager.cs#L58-L60) to return your desired rotation you're calculating in RelativeEuler().

**Comment by zolantris** [comment]
I'll close this when I add a fix to raft. Probably today/tomorrow.

**Comment by zolantris** [comment]
Hmm, so I think there is more to this issue. The snapping rotation even with a patch to RotationMangaer is not in alignment. Guessing snapping point local position will also need a patch.

**Comment by BruceOfTheBow** [comment]
Not quite sure what you mean by that. Is that something on the ValheimRAFT side? Let me know if there's any other info on ComfyGizmo that would be helpful to know.

**Comment by BruceOfTheBow** [comment]
Please reopen if any further questions on ComfyGizmo.
