### ISSUE TITLE
Gizmo Bug ?

### ISSUE THREAD

**Issue by PerfyNormal** [BruceOfTheBow/BruceComfyMods#16]
Can not rotate X-Axis , I do not know if there's a compatibility issue that is causing it.
Y works fine and interface does suggest that I should be able to, but when I use my scroll wheel it doesn't rotate.

bepinex 5.4.2202
planteasily 1.8.0
useequipmentinwater 0.2.4
nofogbruh 1.0.5
Jotunn 2.20.1
AdvancedTerrainModifiers 1.3.2
Server_devcommands 1.81.0
Infinity_Hammer 1.56.0
DeathTweaks 0.9.3
Gizmo 1.10.0

I wasn't able to find any mention of the issue and I don't see errors in the console

**Comment by BruceOfTheBow** [comment]
Does the issue persist with only ComfyGizmo and bepinex installed? If not, you'll have to narrow it down. None of the mods listed here are approved for use on the Comfy server so I can't speak to compatibility.

**Comment by DragonPilot3** [comment]
It's infinity hammer that breaks it, I was having the same issue.
