### ISSUE TITLE
Non-breaking error during startup.

### ISSUE THREAD

**Issue by Sketaful** [BruceOfTheBow/BruceComfyMods#17]
Don't know why but this started show up each time I start the game with Gizmo active.
Everything still seems to work. The game load ok and all the building blocks can be rotated just as they should.

This is more a "Why the errors?" and to let you know just in case it's something easy you know how to fix ;)

ERROR:
<code>[Error  : Unity Log] TypeLoadException: Could not load type ComfyGizmo.Patches.PlayerPatch, ComfyGizmo, Version=1.9.2.0,  Culture=neutral, PublicKeyToken=null while decoding custom attribute: (null)
Stack trace: System.MonoCustomAttrs.GetCustomAttributesBase (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inheritedOnly) (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
System.MonoCustomAttrs.GetCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inherit) (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
System.MonoCustomAttrs.GetCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Boolean inherit) (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
System.Reflection.RuntimeMethodInfo.GetCustomAttributes (System.Boolean inherit) (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
HarmonyLib.PatchTools+<>c__DisplayClass2_0.<GetPatchMethod>b__0 (System.Reflection.MethodInfo m) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate, System.Boolean& found) (at <2a397996daff412691ae4781443e8e88>:0)
System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) (at <2a397996daff412691ae4781443e8e88>:0)
HarmonyLib.PatchTools.GetPatchMethod (System.Type patchType, System.String attributeName) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor..ctor (HarmonyLib.Harmony instance, System.Type type, System.Boolean allowUnannotatedType) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.CreateClassProcessor (System.Type type, System.Boolean allowUnannotatedType) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.PatchAll (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
PlanBuild.Patches.Apply () (at <1b3521b4b98c4a57af1b59922e75f8de>:0)
PlanBuild.PlanBuildPlugin.Awake () (at <1b3521b4b98c4a57af1b59922e75f8de>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:DMD<BepInEx.Bootstrap.Chainloader::Start>()
UnityEngine.GameObject:.cctor()
PlatformTools.Common.SingletonMonoBehaviour`1:get_Instance()
PlatformTools.PlatformManagerInitializer:OnRuntimeMethodLoad()</code>

**Comment by BruceOfTheBow** [comment]
Looks like a compatibility issue with PlanBuild where its attempting to access the ComfyGizmo patch. I'd raise this issue there. Thanks for bringing it to my attention
