### ISSUE TITLE
The bread is not pickable after Bogwitch update

### ISSUE THREAD

**Issue by pengyou200902** [BruceOfTheBow/BruceComfyMods#27]
The bread is not pickable(even manually pressing "E"). Need to destruct the stone baker to pick up the bread. Could someone take a look on that? Other than that, everything is good.

Thank you!

**Comment by pengyou200902** [comment]
My bad, fogot to mention that I am only using ComfyAddAllFuel. That is great functionality though!

**Comment by callumhauber** [comment]
Can confirm, after the Bog Witch Update I can't remove any cooked items from the stone oven or cooking stations over fires. I can still add items to start cooking, just can't remove the cooked ones after. After disabling this mod everything worked normally again.

**Comment by pengyou200902** [comment]
Hi I just tried and can confirm the cooked items are now pickable. The update works great! Appreciate [the update](https://github.com/BruceOfTheBow/BruceComfyMods/commit/4faa09deef9067ff12c9f7fa379ccdbf932fd012)!
