### ISSUE TITLE
Broken with Patch 0.217.22

### ISSUE THREAD

**Issue by Grand-Warchief** [BruceOfTheBow/BruceComfyMods#3]
The newest patch has caused issues with this mod. This is only a post to note that it needs to be updated in case that was not already known. I really love this mod and appreciate having it since it makes mass crafting so much easier.

**Comment by BruceOfTheBow** [comment]
Thanks for the report. I'll be working on updating mods this weekend and will be updating for the recent patch.

**Comment by BruceOfTheBow** [comment]
Fixed with latest version and released on Thunderstore.
