### ISSUE TITLE
[Request] Controller Support

### ISSUE THREAD

**Issue by Yourname942** [BruceOfTheBow/BruceComfyMods#5]
Is it possible to add controller support? Sadly this mod seems to disable all rotations via controller. 

Option A:
controller rotations are left as vanilla & the gizmo works with m+k

Option B: (Ideal)
Gizmo controller rotations are enabled as well as for m+k

Thank you.

**Comment by BruceOfTheBow** [comment]
No plans for explicit controller support. Will review a pull request for that support should you wish to add that functionality.
