### ISSUE TITLE
Save Pintervention State

### ISSUE THREAD

**Issue by randomsteve95370** [BruceOfTheBow/BruceComfyMods#6]
Would it be possible for the state of your enabled and disabled pins to save between sessions? Having to re disable all the players pins I don't want every time I relog reduces the usefulness of the mod by a fair margin. 

Just a suggestion/request

**Comment by BruceOfTheBow** [comment]
Yeah that's a great feature request. I'll take a look at adding this. Thanks for asking

**Comment by BruceOfTheBow** [comment]
Added as feature with Pintervention v1.1.0 and has been pushed to Thunderstore.
