### ISSUE TITLE
ComfyGizmo rotates when using SearsCatalog

### ISSUE THREAD

**Issue by OrianaVenture** [BruceOfTheBow/BruceComfyMods#8]
Using Gizmo v1.9.0 and SearsCatalog v1.4.0 on Valheim 0.217.38:

When selecting pieces in the build menu scrolling rotates the pieces. This is making it very inconvenient to build when swamping pieces frequently. Confirmed it is only an issue when Gizmo is installed, vanilla and other gizmo mods work as expected.

**Comment by BruceOfTheBow** [comment]
This will be fixed with v1.9.1 which I'll release on TS when Comfy Server is updated (planned for 4/14.) Thanks for the bug report!

https://github.com/BruceOfTheBow/BruceComfyMods/blob/9b9c475e95fdbbfb4cfb89b500ece8d55e5bedf3/ComfyGizmo/Patches/PlayerPatch.cs#L37
